name: Main

on: [pull_request]

jobs:
  vm-job:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python_version: 3.7

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby_version: 2.6.3

    - name: Set up Aws Cli
      uses: unfor19/install-aws-cli-action@v1
      id: install-aws-cli
      with:
        version: 2
        run: aws --version
        shell: bash

    - name: Set up pip
      run: python -m pip install --upgrade pip

    - name: Set up LocalStack
      run: |
        docker-compose -f docker-compose.localstack.yml up -d
        while ! curl -s http://localhost:4575 > /dev/null; do echo waiting for localstack; sleep 3; done;
        aws --endpoint-url=http://localhost:4575 sns create-topic --name liam_TestProducer

    - name: Build
      env:
        RAILS_ENV: test
      run: |
        gem install bundler -v 2.1.4
        bundle _2.1.4_ install --jobs 4 --retry 3

    - name: Run tests
      run: |
        RAILS_ENV=test bundle exec rspec -fd
